apiVersion: v1
kind: Service
metadata:
  name: chromadb
  namespace: rag-pdf
  labels:
    app.kubernetes.io/name: chromadb
    app.kubernetes.io/component: database
    app.kubernetes.io/part: "02-networking"
spec:
  # Internal vector database endpoint: http://chromadb:8000
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chromadb
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
